services:
  backend:
    build: ./backend
    container_name: analytica-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on: []
  
  frontend:
    build: ./frontend
    container_name: analytica-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]
