services:
  api:
    build: ./backend
    env_file: .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - DATA_BACKEND=${DATA_BACKEND}
      - DATA_URI=${DATA_URI}
      - DATA_FORMAT=${DATA_FORMAT}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}


  backend:
    build: ./backend
    container_name: analytica-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on: []
  
  frontend:
    build: ./frontend
    container_name: analytica-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]
